# fly.toml app configuration file generated for backendspa on 2025-05-07T22:42:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backendspa'
primary_region = 'eze'

[build]
  builder = 'paketobuildpacks/builder-jammy-base'
  buildpacks = ['paketo-buildpacks/java']

[env]
  BP_JVM_VERSION = '21'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
